//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentOtomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMusteri
    {
        public short MusteriId { get; set; }
        public string MusteriAd { get; set; }
        public string MusteriSoyad { get; set; }
        public string MusteriTc { get; set; }
        public Nullable<bool> MusteriCinsiyet { get; set; }
    }
}
