//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentOtomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblMercedes
    {
        public short ArabaId { get; set; }
        public string ArabaModel { get; set; }
        public string ArabaFiyat { get; set; }
        public Nullable<System.DateTime> ArabaYil { get; set; }
        public string ArabaCategory { get; set; }
    }
}
