//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CarRentOtomation
{
    using System;
    using System.Collections.Generic;
    
    public partial class TblPersonel
    {
        public short PersonelId { get; set; }
        public string PersonelAd { get; set; }
        public string PersonelSoyad { get; set; }
        public string PersonelSifre { get; set; }
        public Nullable<bool> PersonelCinsiyet { get; set; }
    }
}
